language: php
php:
  - '7.3'
  - '7.2'
  - '7.1'
  - nightly
before_script:
  - pecl install ast-0.1.5
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
script: composer test && composer php-compatibility